### ISSUE TITLE
Confusion over FeliCa support on a non-pixel phone

### ISSUE THREAD

**Issue by InsightGit** [kormax/osaifu-keitai-google-pixel#11]
Apologies if this is the wrong place to ask this type of question (feel free to close and say out of scope if so): but I've recently been investigating FeliCa support on my personal unlocked non-pixel phone (a Oneplus 8T, never sold in Japan/had a Japanese model). This phone should by no means have any support for FeliCa, but for some reason when I tap a Japanese transportation IC Card which uses Felica when using NXP TagInfo, it recognizes the card as a FeliCa card and all the information shown on the IC Info seems to be correct and Full Scan says it's "JIS X 6319-4 compatible." I'll attach a screenshot of what I'm seeing on the full scan side of it. In addition, despite these cards not being Suica cards, they all show as Suica cards, but I don't know if that's actually buggy behavior.

Despite these findings, I can find nothing else about this phone (albeit it is on a custom rom that's not OTA) that would indicate it supports FeliCa: no configuration files or anything leads Osaifu Keitai to give the first error telling me to close the application. After initial inspection, it seems that the phone's stock ROM also did not include any sort of FeliCa config files, but I'll keep looking. The only thing that I could think of which would warrant a FeliCa varient of the phone is maybe a Hong Kong version for their Octopus IC card system? But unsure.

I guess my main questions are, if any of y'all know the questions to them:
- What are the differentiating factors between phones that support Osaifu Keitai and the phones that can read FeliCa cards using a tool like NXP TagInfo? I'm guessing all phones which support Osaifu Keitai can read FeliCa cards through TagInfo, but not the other way around?
- Is the problem that's keeping Osaifu Keitai from working in this case a hardware problem or a software/keys problem? Is it commonplace for some non-Japanese Android phones like mine to be able to read FeliCa cards but not able to replicate them?
![signal-2024-04-15-162415_002](https://github.com/kormax/osaifu-keitai-google-pixel/assets/13735132/ef80f4a2-7b30-4745-9527-d01494a5e182)
![signal-2024-04-15-162415_003](https://github.com/kormax/osaifu-keitai-google-pixel/assets/13735132/78c230ab-847b-43bf-9efe-ed89ed360e1e)

Thanks and sorry again if this is the wrong place to ask!

**Comment by kormax** [comment]
Most NFC chips created in the past 10+ years support all common NFC modulation types. 

This list includes:
- A (NXP)
- B (Motorola)
- F (FeliCa)
- V (Vicinity)

So in that case, any modern device with NFC (I'd argue, ANY device with NFC, even a very old one) will be able to read a FeliCa card.

What's the limiting factor for Osaifu Keitai support, is not the NFC chip itself, but the chip which is actually responsible for holding card data and operating it. This chip is called a Secure Element.

- Firstly, this chip is not always included, because It's costly and requires OEM infrastructure to be used properly (as the OEM is responsible for holding the keys and managing applets running on those secure elements).

- Secondly, for a Secure Element chip to be able to run Osaifu-Keitai, it should come preconfigured with code and encryption keys provided by Sony/FeliCa networks. Sony asks money for this capability, so no one outside of Japan bothers to pay for that (Don't mention Apple, they've got a sweetheart deal, which probably includes paying for licensing only when a device activates Osaifu-Keitai for the first time).

That's the only real factor impacting broadness of support.

**Comment by kormax** [comment]
In regards to Octopus support. 

Octopus does not use Osaifu-Keitai infrastructure. 
Instead, as far as I know, at the current moment Octopus uses carrier SIM cards as secure elements. So any phone which has NFC & NFC SWP support is able to emulate an Octopus card.

In the near future, thanks to partnership with Google, Octopus will also be compatible with any phone running an "Android SE Alliance" certified Secure Element. That includes all new flagship devices, and many more coming in the future.

**Comment by InsightGit** [comment]
I see. Thank you for the detailed explanation! Is there anyway to verify the existence (or non-existence) of a Secure Element chip without the keys/config file being present?

**Comment by kormax** [comment]
I can't say on how to detect this for sure, but my gut feeling says that it's possible, at least on the stock ROM. Having root could help with research.

I think you have to dig for files or services which contain `omapi` `se` `secureelement` `clf` in their names or logs.

Beware: even if you find that the chip exists, you won't be able to do anything with it, as only the OEM has the encryption keys needed to establish a proper communication with the chip (and write applets to it, make changes to the configuration). That's the **Secure** part in "Secure Element", and that's by design.

**Comment by InsightGit** [comment]
Makes sense. Thanks for the advice and help!
