### ISSUE TITLE
Not an issue, but...

### ISSUE THREAD

**Issue by izus-specman** [kormax/osaifu-keitai-google-pixel#15]
Guys, sorry for offtop, but as I think, you're the only ones, who can help me :)
I bought my Pixel 8 around two weeks ago. And it has a strange issue with Wallet. Everything else is just perfect, but wallet can work one hour and became totaly useless just in 10-15 minutes. And it happenes absolutely randomly.

I've used NFC Tools on another phone and descovered, that my Pixel sends two types of responses randomly:

First one:

Tag type: JIS 6319-4 (Unknown FeliCa)
Supported technologies: NfcG
Serial Number: 05:FE:E6 ... A2:A3 (Always this number, never changes with this type of reply)
PMm: 0x01188 ... CBFF (Also always the same)
System code: 0xFFFF

Same kind of reply has my ID card.

Second type of reply:

Tag type: ISO 14443-4 (NXP - Mifare Plus)
Supported technologies: IsoDep, NfcA
Serial Number: Always different with XX:XX:XX:XX mask
ATQA: 0x0004
SAK: 0x20

Same kind of reply has every bank card I have, iPhone 15 with Apple Pay and any other NFC on Android which I can find. I'm from Kazakhstan, my phone (according to https://store.google.com/us/device-authenticity?id=IMEI) intended for CA,FI,IN,MA,US. So, nothing common with Japan... but it works like some FeliCa is 'burned' into it's NFC. So, while everyone here is trying to enable FeliCa support, I want to know how to disable it totally :) Any help?

P.S. Phone was new, sealed, so, I doubt that someone can used it before, root it and put some data in it...

**Comment by kormax** [comment]
> Everything else is just perfect, but wallet can work one hour and became totaly useless just in 10-15 minutes

What does "useless" mean? The phone stops reacting to NFC readers, or it detects a reader but fails to perform a transaction?
Also, which Android version and phone model do you use?

> I've used NFC Tools on another phone and discovered, that my Pixel sends two types of responses randomly:

This is entirely normal for Android devices, as they have NFC for all modes (A, B, F) turned on passively. The reason you're getting different responses via an app, is because the application you're using does not expect this, and it displays the first technology that your reading phone polled for at the moment of tapping.
The same thing does not happen for Apple devices, as they have NFC routing turned off by default, and when a card is authenticated, it only activates respective technology used by that particular card.

> Serial Number: 05:FE:E6 ... A2:A3 (Always this number, never changes with this type of reply)

NFC-F, unlike other NFC types, requires static iDM and PMM values as they are used throughout the FeliCa protocol (such as for KDF input when performing authentication, balance tear-off prevention, etc). So this behaviour is entirely normal.

> but it works like some FeliCa is 'burned' into it's NFC. So, while everyone here is trying to enable FeliCa support, I want to know how to disable it totally :) Any help?

You cannot disable FeliCa separately from other NFC types. Not without root (But I don't know what module can be used for that). Android 15 allows to do that, but it has to be implemented by NFC application developer. So you have to wait for it to happen.

**Comment by izus-specman** [comment]
> What does "useless" mean? The phone stops reacting to NFC readers, or it detects a reader but fails to perform a transaction?
> Also, which Android version and phone model do you use?

Wallet app stop reacting, but readers (POS-terminal in stores) drop an error ('Application not found' e.g.) if hold phone enough long around it. If quickly move phone toward and backwards to POS-terminal it's trying to read 'card' any time, phone is near. But only trying... Not reading. If hold phone enough time, there is an error (just a red icon, or 'Application not found' - depends on POS). If I use some NFC-reader (e.g. another phone with NFS Tools) it got a reply EVERY TIME, but replies are different (two types), and there is no pattern. Just random.

Also, I'm using Pixel 8 and Android 14. I've tried Android 15 Beta 4 - same issue. Factory Reset (via Settings app) does nothing with this issue... Maybe I should try reset via service menu... If pixel has one...

> This is entirely normal for Android devices

Hm... Maybe I've tried it only with quite old Android devices... but I haven't found any phone which generates JIS 6319-4 reply...

> Android 15 allows to do that, but it has to be implemented by NFC application developer. So you have to wait for it to happen.

Ok. Let's wait. Almost disabled Google Wallet is uncomfortable but not unbearable. I really like this phone. It's perfect (as for me), but this NFC issue... it's kinda... hmm... annoying. While trying to figure out, I've found a few Pixel 8/8 Pro users, who get the same issue with their phone in last weeks... But I was messed up with this double replies - I though, that this was a root of problem. But, if you say, that it's ok... maybe it's just a crappy Google Wallet version...

**Comment by kormax** [comment]
"Application not found" error means that POS is able to successfully communicate with your device, but the later one says that no payment applications are available (it happens on ISODEP -> ISO7816 layers):

That could happen due to one of the following reasons:

- For some reason, GMS and/or Wallet applications encounter issues during operation, which makes them crash/unresponsive, hence POS thinks that payment is unavailable. In this situation I would have advised to reinstall the OS, but you say that you did already, so IDK;
- Wallet is not selected as default payment app;
- You have some other application interfering with Wallet. For instance, this could happen with apps that modify system authentication behaviour (BLE or locaton unlock).
- You might have another card in the way of the phone, like in a phone case.
- POS just doesn't support the payment network your card is using.


As for felica, it shouldn't impact payment at all, because all payment terminals (outside of Japan and HK) only poll for NFC Type A and B. They wouldn't know about felica. Your other phone knows because the app has this technology type turned on. That's it.

**Comment by izus-specman** [comment]
>     For some reason, GMS and/or Wallet applications encounter issues during operation, which makes them crash/unresponsive, hence POS thinks that payment is unavailable. In this situation I would have advised to reinstall the OS, but you say that you did already, so IDK;

I came to the same conclusion. Also, I admit that it can be shitty Wallet app update... It happens from time to time on my previous devices.

>     Wallet is not selected as default payment app;

I've tried both way. Settings allow only two options: Google Wallet and None. Anyways, when Wallet app is running, it should work even if it's not default... but it's not...

>    You have some other application interfering with Wallet. For instance, this could happen with apps that modify system authentication behaviour (BLE or locaton unlock).

Hmmm... That's a variant, actually. I didn't use location unlock (I've used it on my Nokia G21 and it doesn't affect wallet app), but BLE... is there any way to detect, which app can fire up this feature? The only assumption is Zepp Life (MiBand fitness bracelet application)... But it was also on my prev. Nokia G21 and everything works just find... but there was Android 13...

> You might have another card in the way of the phone, like in a phone case.

Not an option. No other card and/or cases. Just 'naked' phone :)

>  POS just doesn't support the payment network your card is using.
Also not an option, I think. I've used same card on the same POS on my prev phone and it works perfectly. Also, as I wrote at the beginning - even this Pixel 8 sometimes got a kick and works just fine... but only for some not obvious timeslot. I can pay without any issues, but if I return in the same store next day or in a few hours - Wallet became useless... 

Anyway, thank you. It's a lot of info, especcialy if compare it with typical Reddit/Google Community comments like 'Reboot your phone', ' Delete your card and add them again' or a bunch of other stereotypical troubleshooting options, which I've tried several times :)
