### ISSUE TITLE
Uninstall com.google.android.pixelnfc using App Manager (F-Droid)?

### ISSUE THREAD

**Issue by ericshu6** [kormax/osaifu-keitai-google-pixel#17]
There's a great app that allows you to uninstall system apps called [App Manager](https://muntashirakon.github.io/AppManager/en/). It uses ADB over wireless debugging to uninstall system apps and other apps without needing a computer. I don't have a Google Pixel, so I just wanted to put this out there in case if anyone wants to try uninstalling `com.google.android.pixelnfc`.

**Comment by kormax** [comment]
I've glanced over this approach in [section dedicated to unsuccessful ROOT-less methods](https://github.com/kormax/osaifu-keitai-google-pixel?tab=readme-ov-file#overcome-the-limitations-without-root).

Sadly, it does not work because system apps are not **actually** uninstallable. What you're suggesting will only "remove" it for current user, but it will stay in the system, preventing an install of modified copy or an app that declares the same provider.
