### ISSUE TITLE
Mode1 Retro ii support and other phones such as Xiaomi

### ISSUE THREAD

**Issue by mathieujobin** [kormax/osaifu-keitai-google-pixel#19]
Thank you for working on this important issue.
it is such a pain we can't use Suica or Pasmo on the favorite phones we choose to buy.

Do you think it would be possible to help with other non-pixel devices?

**Comment by kormax** [comment]
The thing about Pixel devices is that it had both the hardware and software support for Osaifu-Keitai built-in on all models regardless of region, with it being disabled with a very simple software check, which was easy to bypass.

I can't really say anything about other devices - that is up to the people who own them to check if such bypass could help, or they're SOL because the device does not have a secure element, osaifu-keitai applet, or the required parts of the software stack.
