### ISSUE TITLE
LSPatch?

### ISSUE THREAD

**Issue by BakedCrossiant** [kormax/osaifu-keitai-google-pixel#4]
Does the module used with Xposed/LSposed framework work with LSPatch as well? If so, it can be done without root access.

**Comment by kormax** [comment]
Hello.

I haven't used LSPatch, but it looks like that it **modifies** the APK [which wouldn't work because it's a system app](https://github.com/kormax/osaifu-keitai-google-pixel?tab=readme-ov-file#overcome-the-limitations-without-root). 

But you can try if you have time for that. Would appreciate if you can confirm or deny that assumption.
